language: python
notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky

install: "pip install -r requirements.txt"

script: 
  - python -m unittest discover
  - coverage run --omit=Tests/*,/home/* -m unittest discover Tests
after_success: coveralls