language: python
notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky

install: "pip install -r requirements.txt"

script: python --version
script: python TestS3Service.py
script: python TestSchedulerController.py