language: python
notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky

install: "pip install -r requirements.txt"

script: python ./services/S3Service/TestS3Service.py
script: python ./controllers/SchedulerController/TestSchedulerController.py