language: python
notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky

install: "pip install -r requirements.txt"

script: 
  - python ./Tests/TestS3Service.py
  - python ./Tests/TestXMLConverterService.py
  - python TestSchedulerController.py
  # - python ./Tests/LiveService/testLiveService.py
  - coverage run --source=services TestSchedulerController.py
after_success: coveralls