language: python
notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky

install: "pip install -r requirements.txt"

script: 
  - python -m unittest discover Tests
  - coverage run --omit=Tests/*,/home/travis/virtualenv/python2.7.13/lib/python2.7/* -m unittest discover Tests
after_success: coveralls